#Data Ingestion by loading CSV data

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/sample_data/rows.csv.zip')

/tmp/ipykernel_721/591282842.py:1: DtypeWarning: Columns (4,5,6,11,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/sample_data/rows.csv.zip')

#Data Understanding by Displaying Its Rows, Columns, Statistical and Concise Descriptions, Column Names, and Data Types
##To explore and understand your dataset thoroughly in Python using Pandas, you can use the following functions:

###Displaying Rows: Use df.head(n) to view the first n rows and df.tail(n) to view the last n rows of the DataFrame.

###Displaying Columns & Shape: Use df.shape to check the total number of rows and columns, and df.columns to retrieve all column names.

###Concise Descriptions: Use df.info() to get a concise summary of the DataFrame, including the non-null count and data types for every column.

###Statistical Descriptions: Use df.describe() to generate descriptive statistics (such as mean, standard deviation, min, max, and percentiles) for all numerical columns.

In [ ]:
df.shape

(1282355, 18)

In [ ]:
df.describe()

       Complaint ID
count  1.282355e+06
mean   1.929831e+06
std    9.645326e+05
min    1.000000e+00
25%    1.124152e+06
50%    2.123218e+06
75%    2.798886e+06
max    3.238682e+06

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1282355 entries, 0 to 1282354
Data columns (total 18 columns):
 #   Column                        Non-Null Count    Dtype
---  ------                        --------------    -----
 0   Date received                 1282355 non-null  object
 1   Product                       1282355 non-null  object
 2   Sub-product                   1047189 non-null  object
 3   Issue                         1282355 non-null  object
 4   Sub-issue                     751169 non-null   object
 5   Consumer complaint narrative  383564 non-null   object
 6   Company public response       449082 non-null   object
 7   Company                       1282355 non-null  object
 8   State                         1262955 non-null  object
 9   ZIP code                      1167057 non-null  object
 10  Tags                          175643 non-null   object
 11  Consumer consent provided?    690654 non-null   object
 12  Submitted via                 1282355 non-null  object
 13  Date sent to company          1282355 non-null  object
 14  Company response to consumer  1282348 non-null  object
 15  Timely response?              1282355 non-null  object
 16  Consumer disputed?            768501 non-null   object
 17  Complaint ID                  1282355 non-null  int64
dtypes: int64(1), object(17)
memory usage: 176.1+ MB

In [ ]:
df.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID'],
      dtype='object')

In [ ]:
df.dtypes

Date received                   object
Product                         object
Sub-product                     object
Issue                           object
Sub-issue                       object
Consumer complaint narrative    object
Company public response         object
Company                         object
State                           object
ZIP code                        object
Tags                            object
Consumer consent provided?      object
Submitted via                   object
Date sent to company            object
Company response to consumer    object
Timely response?                object
Consumer disputed?              object
Complaint ID                     int64
dtype: object

In [ ]:
df.dtypes.value_counts

<bound method IndexOpsMixin.value_counts of Date received                   object
Product                         object
Sub-product                     object
Issue                           object
Sub-issue                       object
Consumer complaint narrative    object
Company public response         object
Company                         object
State                           object
ZIP code                        object
Tags                            object
Consumer consent provided?      object
Submitted via                   object
Date sent to company            object
Company response to consumer    object
Timely response?                object
Consumer disputed?              object
Complaint ID                     int64
dtype: object>

In [ ]:
df.head(10)

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,05/10/2019,Checking or savings account,Checking account,Managing an account,Problem using a debit or ATM card,NaN,NaN,NAVY FEDERAL CREDIT UNION,FL,328XX,Older American,NaN,Web,05/10/2019,In progress,Yes,NaN,3238275
1,05/10/2019,Checking or savings account,Other banking product or service,Managing an account,Deposits and withdrawals,NaN,NaN,BOEING EMPLOYEES CREDIT UNION,WA,98204,NaN,NaN,Referral,05/10/2019,Closed with explanation,Yes,NaN,3238228
2,05/10/2019,Debt collection,Payday loan debt,Communication tactics,Frequent or repeated calls,NaN,NaN,CURO Intermediate Holdings,TX,751XX,NaN,NaN,Web,05/10/2019,Closed with explanation,Yes,NaN,3237964
3,05/10/2019,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Old information reappears or never goes away,NaN,NaN,Ad Astra Recovery Services Inc,LA,708XX,NaN,NaN,Web,05/10/2019,Closed with explanation,Yes,NaN,3238479
4,05/10/2019,Checking or savings account,Checking account,Managing an account,Banking errors,NaN,NaN,ALLY FINANCIAL INC.,AZ,85205,NaN,NaN,Postal mail,05/10/2019,In progress,Yes,NaN,3238460
5,05/10/2019,Mortgage,Other type of mortgage,Closing on a mortgage,NaN,NaN,NaN,Statebridge Company,NJ,08302,NaN,NaN,Web,05/10/2019,Closed with explanation,Yes,NaN,3237885
6,05/10/2019,Debt collection,Other debt,Attempts to collect debt not owed,Debt is not yours,NaN,NaN,"Diversified Consultants, Inc.",TX,NaN,Servicemember,NaN,Web,05/10/2019,In progress,Yes,NaN,3238585
7,05/10/2019,Student loan,Federal student loan servicing,Struggling to repay your loan,Problem lowering your monthly payments,NaN,NaN,Student Loan Direct,TX,773XX,Older American,NaN,Web,05/10/2019,Closed with explanation,Yes,NaN,3238221
8,05/10/2019,Debt collection,Other debt,Attempts to collect debt not owed,Debt was paid,NaN,NaN,"Diversified Consultants, Inc.",SC,296XX,Servicemember,NaN,Web,05/10/2019,In progress,Yes,NaN,3238545
9,05/10/2019,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,CONTRACT CALLERS INC,MD,20774,NaN,NaN,Web,05/10/2019,In progress,Yes,NaN,3238458

In [ ]:
df.tail(10)

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
1282345,12/01/2011,Credit card,NaN,Billing statement,NaN,NaN,NaN,"CITIBANK, N.A.",CA,92629,NaN,NaN,Web,12/05/2011,Closed without relief,No,No,2400
1282346,12/01/2011,Credit card,NaN,Billing disputes,NaN,NaN,NaN,"BANK OF AMERICA, NATIONAL ASSOCIATION",FL,32720,NaN,NaN,Referral,12/01/2011,Untimely response,No,No,2066
1282347,12/01/2011,Credit card,NaN,Credit reporting,NaN,NaN,NaN,CAPITAL ONE FINANCIAL CORPORATION,MD,21218,Older American,NaN,Web,12/02/2011,Closed with relief,Yes,Yes,2261
1282348,12/01/2011,Credit card,NaN,Balance transfer,NaN,NaN,NaN,JPMORGAN CHASE & CO.,FL,34997,NaN,NaN,Referral,12/01/2011,Closed with relief,Yes,No,2154
1282349,12/01/2011,Mortgage,Home equity loan or line of credit,"Loan modification,collection,foreclosure",NaN,NaN,NaN,"BANK OF AMERICA, NATIONAL ASSOCIATION",MI,48197,NaN,NaN,Phone,12/02/2011,Closed without relief,No,No,2231
1282350,12/01/2011,Credit card,NaN,Credit determination,NaN,NaN,NaN,"CITIBANK, N.A.",MO,63301,NaN,NaN,Web,12/02/2011,Closed with relief,Yes,No,2396
1282351,12/01/2011,Mortgage,Conventional fixed mortgage,"Loan modification,collection,foreclosure",NaN,NaN,NaN,"BANK OF AMERICA, NATIONAL ASSOCIATION",OH,45248,NaN,NaN,Web,12/06/2011,Closed without relief,No,No,2323
1282352,12/01/2011,Credit card,NaN,Billing disputes,NaN,NaN,NaN,JPMORGAN CHASE & CO.,OH,43207,NaN,NaN,Referral,12/01/2011,Closed with relief,Yes,No,2126
1282353,12/01/2011,Mortgage,Conventional adjustable mortgage (ARM),"Loan servicing, payments, escrow account",NaN,NaN,NaN,"BANK OF AMERICA, NATIONAL ASSOCIATION",CO,80920,NaN,NaN,Web,12/01/2011,Closed with relief,Yes,No,2315
1282354,12/01/2011,Credit card,NaN,Billing disputes,NaN,NaN,NaN,"CITIBANK, N.A.",WA,98275,NaN,NaN,Web,12/11/2011,Closed with relief,Yes,No,2329